"TimeUTC","timestampInMs","requestPath","requestMethod","requestQueryString","responseStatusCode","requestId","requestUserAgent","level","environment","branch","vercelCache","type","function","host","deploymentDomain","deploymentId","durationMs","region","maxMemoryUsed","memorySize","message","projectId","traceId","sessionId","invocationId","instanceId","concurrency"
"2025-08-26 02:24:45",1756175085831,"proofofputt-backend.vercel.app/favicon.ico","GET","",-1,"rxjkt-1756175083034-36d4bccfbb9b","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36","error","production","main","","lambda","/api.py","proofofputt-backend.vercel.app","proofofputt-backend.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J329HT91GAGDPA0KMD3E8F","",-1
"2025-08-26 02:24:43",1756175083066,"proofofputt-backend.vercel.app/favicon.ico","GET","",500,"rxjkt-1756175083034-36d4bccfbb9b","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36","error","production","main","","lambda","/api.py","proofofputt-backend.vercel.app","proofofputt-backend.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",2745,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J329HT91GAGDPA0KMD3E8F","",1
"2025-08-26 02:24:42",1756175082723,"proofofputt-backend.vercel.app/","GET","",-1,"hz59w-1756175079935-530446bb710d","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36","error","production","main","","lambda","/api.py","proofofputt-backend.vercel.app","proofofputt-backend.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J326HPC42QT46EYZTDVHB7","",-1
"2025-08-26 02:24:39",1756175079990,"proofofputt-backend.vercel.app/","GET","",500,"hz59w-1756175079935-530446bb710d","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36","error","production","main","","lambda","/api.py","proofofputt-backend.vercel.app","proofofputt-backend.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",2709,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J326HPC42QT46EYZTDVHB7","",1
"2025-08-26 02:24:08",1756175048304,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",-1,"lwhx9-1756175045135-042f3e6b7a38","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J314HRM25Z4SHZ2P8KQWXS","",-1
"2025-08-26 02:24:05",1756175045176,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",500,"lwhx9-1756175045135-042f3e6b7a38","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3112,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J314HRM25Z4SHZ2P8KQWXS","",1
"2025-08-26 02:24:04",1756175044073,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",-1,"b6qv9-1756175040887-2f2e8db32244","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J310D6REVW9WS7GC9H38C0","",-1
"2025-08-26 02:24:00",1756175040934,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",500,"b6qv9-1756175040887-2f2e8db32244","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3115,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J310D6REVW9WS7GC9H38C0","",1
"2025-08-26 02:24:00",1756175040848,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"7p2q5-1756175037565-006c4e886ce3","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30X8JP5TY9T5FEGY4W342","",-1
"2025-08-26 02:23:57",1756175037714,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"7p2q5-1756175037565-006c4e886ce3","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3113,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30X8JP5TY9T5FEGY4W342","",1
"2025-08-26 02:23:55",1756175035484,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"qb4ch-1756175032349-3ec5ab12a6ea","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30R2CC98R0SHM7N8P6EXS","",-1
"2025-08-26 02:23:52",1756175032396,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"qb4ch-1756175032349-3ec5ab12a6ea","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3072,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30R2CC98R0SHM7N8P6EXS","",1
"2025-08-26 02:23:51",1756175031230,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"kccgh-1756175028060-cb87315bf397","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30KW5B4MZ0FC5PDGMJV56","",-1
"2025-08-26 02:23:48",1756175028228,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"n6dvd-1756175025401-6046c2bcff57","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30H924VVQG7CVZNH72W7M","",-1
"2025-08-26 02:23:48",1756175028101,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"kccgh-1756175028060-cb87315bf397","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3107,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30KW5B4MZ0FC5PDGMJV56","",1
"2025-08-26 02:23:48",1756175028092,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",-1,"hlh55-1756175024970-1ed834ccb4fb","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30GVQ0K68349CZ2R7G71J","",-1
"2025-08-26 02:23:47",1756175027921,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",-1,"5fjnz-1756175021022-6fc8650dcc1e","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30D07B91R6BGTPHKYE811","",-1
"2025-08-26 02:23:47",1756175027625,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",-1,"prwbd-1756175024452-e7febdfa2729","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30GBD04N8TMGM45K8YTQB","",-1
"2025-08-26 02:23:45",1756175025442,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"n6dvd-1756175025401-6046c2bcff57","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",2756,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30H924VVQG7CVZNH72W7M","",1
"2025-08-26 02:23:45",1756175025154,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",-1,"jndm4-1756175018897-d6eb0771185f","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30B2G00Q32W6HDTCK3CNQ","",-1
"2025-08-26 02:23:45",1756175025015,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",500,"hlh55-1756175024970-1ed834ccb4fb","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3055,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30GVQ0K68349CZ2R7G71J","",1
"2025-08-26 02:23:44",1756175024972,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"j7d7j-1756175021782-d77d4ce903c4","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30DR1XPF7JQ9P7BFV3CB6","",-1
"2025-08-26 02:23:44",1756175024493,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",500,"prwbd-1756175024452-e7febdfa2729","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3119,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30GBD04N8TMGM45K8YTQB","",1
"2025-08-26 02:23:43",1756175023384,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",-1,"kccgh-1756175020212-7bef5ebed3d4","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30C7125K1Q696BJWZPXP5","",-1
"2025-08-26 02:23:42",1756175022106,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",-1,"g7dnm-1756175014812-cbce081a69e4","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30776WQQ1YBPR95F2KQRG","",-1
"2025-08-26 02:23:41",1756175021825,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"j7d7j-1756175021782-d77d4ce903c4","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3131,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30DR1XPF7JQ9P7BFV3CB6","",1
"2025-08-26 02:23:41",1756175021763,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",-1,"56hdl-1756175014805-88bd21ebf8b0","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J3077BJ0QK012ZJK05P7E1","",-1
"2025-08-26 02:23:41",1756175021622,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",-1,"6wjv6-1756175018885-b711cba57c4c","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30B0Y35VV876CNPVYTFSQ","",-1
"2025-08-26 02:23:41",1756175021063,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",500,"5fjnz-1756175021022-6fc8650dcc1e","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3188,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30D07B91R6BGTPHKYE811","",1
"2025-08-26 02:23:40",1756175020257,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",500,"kccgh-1756175020212-7bef5ebed3d4","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3114,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30C7125K1Q696BJWZPXP5","",1
"2025-08-26 02:23:40",1756175020171,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"kccgh-1756175016974-ab8bfa97f511","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J3092CPX9JPKXDX3XPQM0F","",-1
"2025-08-26 02:23:39",1756175019088,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",500,"jndm4-1756175018897-d6eb0771185f","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",2769,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30B2G00Q32W6HDTCK3CNQ","",1
"2025-08-26 02:23:39",1756175019038,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",500,"6wjv6-1756175018885-b711cba57c4c","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",2567,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30B0Y35VV876CNPVYTFSQ","",1
"2025-08-26 02:23:37",1756175017036,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"kccgh-1756175016974-ab8bfa97f511","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3117,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J3092CPX9JPKXDX3XPQM0F","",1
"2025-08-26 02:23:35",1756175015147,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",500,"56hdl-1756175014805-88bd21ebf8b0","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3054,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J3077BJ0QK012ZJK05P7E1","",1
"2025-08-26 02:23:35",1756175015142,"proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app/","GET","",500,"g7dnm-1756175014812-cbce081a69e4","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","proofofputt-backend-j1a638qui-nicholas-kirwans-projects.vercel.app","dpl_8611sMQ3p5chtCKu6axHcHGTZ4r5",3229,"iad1",156,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J30776WQQ1YBPR95F2KQRG","",1
"2025-08-26 02:23:34",1756175014886,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"74mvq-1756175011695-eeff6cbad096","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J303WPXVQB8ZECNC0T25WX","",-1
"2025-08-26 02:23:31",1756175011734,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"74mvq-1756175011695-eeff6cbad096","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3132,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J303WPXVQB8ZECNC0T25WX","",1
"2025-08-26 02:23:30",1756175010578,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"4zt74-1756175007372-31d30e048490","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2ZZNS1RXSB19679V1TAQM","",-1
"2025-08-26 02:23:27",1756175007617,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",-1,"xl76t-1756175004293-9695c32c1e2d","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2ZWRYK3X03B8S5YNX3ZVD","",-1
"2025-08-26 02:23:27",1756175007417,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"4zt74-1756175007372-31d30e048490","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3143,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2ZZNS1RXSB19679V1TAQM","",1
"2025-08-26 02:23:24",1756175004446,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",500,"xl76t-1756175004293-9695c32c1e2d","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3156,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2ZWRYK3X03B8S5YNX3ZVD","",1
"2025-08-26 02:23:23",1756175003552,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",-1,"njlbq-1756175000365-5d233c3f9eec","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2ZRTXWTNYMSGCRYGRZ44A","",-1
"2025-08-26 02:23:20",1756175000413,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",500,"njlbq-1756175000365-5d233c3f9eec","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3123,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2ZRTXWTNYMSGCRYGRZ44A","",1
"2025-08-26 02:22:59",1756174979288,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"9pwg2-1756174976009-1a511e253d9f","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2Z151TB0SEJA999TW49F6","",-1
"2025-08-26 02:22:59",1756174979286,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"rhhwl-1756174976017-5e9b0fa198bc","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2Z17AY2XRV991QBG4W3J9","",-1
"2025-08-26 02:22:56",1756174976234,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"rhhwl-1756174976017-5e9b0fa198bc","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3039,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2Z17AY2XRV991QBG4W3J9","",1
"2025-08-26 02:22:56",1756174976161,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"9pwg2-1756174976009-1a511e253d9f","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3107,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2Z151TB0SEJA999TW49F6","",1
"2025-08-26 02:22:55",1756174975939,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",-1,"qb4ch-1756174969020-57b51299e307","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2YTA8MGRHEK2M8P433XXZ","",-1
"2025-08-26 02:22:55",1756174975824,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",-1,"q8np6-1756174968950-4c2e64722fd0","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2YT86EXDZHW4KWG3174MG","",-1
"2025-08-26 02:22:52",1756174972225,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",-1,"lq6sv-1756174964880-e4dee5bed40a","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2YPD2KZT98DA7BP1XJ616","",-1
"2025-08-26 02:22:52",1756174972217,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",-1,"cjppz-1756174964950-e425aded6f97","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2YPHWMYT8F0AA5ZVPAJ8Q","",-1
"2025-08-26 02:22:49",1756174969160,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",500,"qb4ch-1756174969020-57b51299e307","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3156,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2YTA8MGRHEK2M8P433XXZ","",1
"2025-08-26 02:22:49",1756174969094,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",500,"q8np6-1756174968950-4c2e64722fd0","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3080,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2YT86EXDZHW4KWG3174MG","",1
"2025-08-26 02:22:45",1756174965308,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",500,"cjppz-1756174964950-e425aded6f97","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3178,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2YPHWMYT8F0AA5ZVPAJ8Q","",1
"2025-08-26 02:22:45",1756174965154,"proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app/","GET","",500,"lq6sv-1756174964880-e4dee5bed40a","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","proofofputt-backend-n6m1nluli-nicholas-kirwans-projects.vercel.app","dpl_F3Ka6PuK54BNnwFTqoi3jHdC26Z5",3219,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J2YPD2KZT98DA7BP1XJ616","",1
"2025-08-26 02:04:28",1756173868332,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",-1,"d5kjc-1756173865094-866921f170b1","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1X45VKRW8FZSJVWEGYVS6","",-1
"2025-08-26 02:04:25",1756173865147,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",500,"d5kjc-1756173865094-866921f170b1","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3166,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1X45VKRW8FZSJVWEGYVS6","",1
"2025-08-26 02:04:24",1756173864012,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",-1,"fnwp7-1756173860726-e38535d93f8e","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WZX5K0MQEDWWB9G0VBQ2","",-1
"2025-08-26 02:04:20",1756173860773,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.png","GET","",500,"fnwp7-1756173860726-e38535d93f8e","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3215,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WZX5K0MQEDWWB9G0VBQ2","",1
"2025-08-26 02:04:20",1756173860685,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"mdzx7-1756173857358-ab0823739bc1","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WWKPWFJGTW0PNT815HHC","",-1
"2025-08-26 02:04:17",1756173857398,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"mdzx7-1756173857358-ab0823739bc1","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3270,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WWKPWFJGTW0PNT815HHC","",1
"2025-08-26 02:04:15",1756173855774,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"vdv9f-1756173852257-709dfbd51e6b","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WQM2XT51GAPRBX8A4EQQ","",-1
"2025-08-26 02:04:15",1756173855276,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"w8jc6-1756173851863-58dd16b918c4","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WQ853RTE31BKJHTS89BE","",-1
"2025-08-26 02:04:12",1756173852290,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"vdv9f-1756173852257-709dfbd51e6b","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3466,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WQM2XT51GAPRBX8A4EQQ","",1
"2025-08-26 02:04:12",1756173852104,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",-1,"lx7d9-1756173848462-cf63686ccef2","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WKX7YMAEBTTZYXCPT9D9","",-1
"2025-08-26 02:04:11",1756173851909,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"w8jc6-1756173851863-58dd16b918c4","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3350,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WQ853RTE31BKJHTS89BE","",1
"2025-08-26 02:04:10",1756173850715,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"s85qp-1756173847314-d20c67798e7f","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WJSV27Y4R4EMX8SVJGYN","",-1
"2025-08-26 02:04:08",1756173848487,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",500,"lx7d9-1756173848462-cf63686ccef2","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3601,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WKX7YMAEBTTZYXCPT9D9","",1
"2025-08-26 02:04:07",1756173847775,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",-1,"ndxvp-1756173844235-babeb1a6c3e8","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WFWHF72F70NXHA0S8XP6","",-1
"2025-08-26 02:04:07",1756173847355,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"s85qp-1756173847314-d20c67798e7f","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3342,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WJSV27Y4R4EMX8SVJGYN","",1
"2025-08-26 02:04:04",1756173844369,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",500,"ndxvp-1756173844235-babeb1a6c3e8","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3377,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WFWHF72F70NXHA0S8XP6","",1
"2025-08-26 02:04:03",1756173843642,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",-1,"dxkmm-1756173840285-5b7160435804","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WBY7NE0357H3S5X89N45","",-1
"2025-08-26 02:04:03",1756173843494,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"8brdn-1756173840188-958fd3cb4348","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WBY11GR9H6HGJNXNPNMS","",-1
"2025-08-26 02:04:02",1756173842365,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",-1,"42h57-1756173839502-8a02de06a745","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WB5TZGNYWHSE53XZ4MTE","",-1
"2025-08-26 02:04:00",1756173840327,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",500,"dxkmm-1756173840285-5b7160435804","vercel-favicon/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3298,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WBY7NE0357H3S5X89N45","",1
"2025-08-26 02:04:00",1756173840321,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"8brdn-1756173840188-958fd3cb4348","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3157,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WBY11GR9H6HGJNXNPNMS","",1
"2025-08-26 02:04:00",1756173840106,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",-1,"bt48n-1756173833107-2072babac44f","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1W52DGYCM1AKYJNTHA1ES","",-1
"2025-08-26 02:03:59",1756173839546,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/favicon.ico","GET","",500,"42h57-1756173839502-8a02de06a745","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",2802,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1WB5TZGNYWHSE53XZ4MTE","",1
"2025-08-26 02:03:59",1756173839410,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",-1,"b6qv9-1756173833217-19ecd2669753","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1W54Q2YBK5F2V88NGJ7K7","",-1
"2025-08-26 02:03:56",1756173836524,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",-1,"56hdl-1756173829146-57c4f24c060f","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1W1D6SMVWJPR9XTAHFHCE","",-1
"2025-08-26 02:03:56",1756173836324,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",-1,"lq6sv-1756173829037-ebc44f615cf5","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",-1,"iad1",-1,-1,"Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.
Traceback (most recent call last):
File ""/var/task/vc__handler__python.py"", line 14, in <module>
__vc_spec.loader.exec_module(__vc_module)
File ""<frozen importlib._bootstrap_external>"", line 999, in exec_module
File ""<frozen importlib._bootstrap>"", line 488, in _call_with_frames_removed
File ""/var/task/api.py"", line 19, in <module>
import data_manager
File ""/var/task/data_manager.py"", line 5, in <module>
from google.cloud.sql.connector import Connector, IPTypes
ModuleNotFoundError: No module named 'google.cloud.sql'
Python process exited with exit status: 1. The logs above can help with debugging the issue.","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1W1D79TTRHZRY4THEKEZ9","",-1
"2025-08-26 02:03:53",1756173833367,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",500,"b6qv9-1756173833217-19ecd2669753","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",2765,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1W54Q2YBK5F2V88NGJ7K7","",1
"2025-08-26 02:03:53",1756173833293,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",500,"bt48n-1756173833107-2072babac44f","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3117,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1W52DGYCM1AKYJNTHA1ES","",1
"2025-08-26 02:03:49",1756173829543,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",500,"lq6sv-1756173829037-ebc44f615cf5","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3149,"iad1",157,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1W1D79TTRHZRY4THEKEZ9","",1
"2025-08-26 02:03:49",1756173829542,"proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app/","GET","",500,"56hdl-1756173829146-57c4f24c060f","vercel-screenshot/1.0","error","production","main","","lambda","/api.py","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","proofofputt-backend-a6g2idkq6-nicholas-kirwans-projects.vercel.app","dpl_F64Zot3mqon5KMcijMTperQX2Fax",3249,"iad1",158,2048,"","prj_vzDqzUy8vbtGgTYmqMKjOWC9LLFD","","","01K3J1W1D6SMVWJPR9XTAHFHCE","",1
